services:
  # Postgres
  #######
  postgres-vector:
    image: pgvector/pgvector:pg18
    shm_size: 128mb
    volumes:
      # Beware conflicts with postgres
      # - type: tmpfs
      #   target: /dev/shm
      #   tmpfs:
      #     size: 134217728 # 128*2^20 bytes = 128Mb
      - ./persistent-data/postgres-vector:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres-vector
    ports:
      - target: 5432
        published: ${POSTGRES_VECTOR_PORT:-5433}
        mode: ingress
    deploy:
      placement: 
        constraints: 
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_vector_password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_USER: ${POSTGRES_VECTOR_USER:-postgres_vector}
    secrets:
      - postgres_vector_password

networks:
  default:
    external: true
    name: ${NETWORK}

secrets:
   postgres_vector_password:
     file: ./docker-secrets/postgres_vector_password.txt