services:
  wireguard:
    environment:
    #  Optional:
    #  - PORT=51821
    #  - HOST=0.0.0.0
     - INSECURE=${WG_EASY_INSECURE_DASHBOARD}
    # REQUIRED: Your server's public IP or domain
     - WG_HOST=${WG_HOST}

    # Default subnet for VPN clients
    #  - WG_DEFAULT_ADDRESS=10.8.0.x
     - WG_DEFAULT_DNS=1.1.1.1,8.8.8.8

    # Optional but recommended
     - WG_ALLOWED_IPS=0.0.0.0/0,::/0
     - WG_PERSISTENT_KEEPALIVE=25

    image: ghcr.io/wg-easy/wg-easy:15
    networks:
      wg:
        ipv4_address: 192.168.177.100
    volumes:
      - ./data:/etc/wireguard
      - /lib/modules:/lib/modules:ro
    ports:
      - target: 51820
        published: ${WG_EASY_PORT_UDP}
        protocol: udp
        mode: host
      - target: 51821
        published: ${WG_EASY_PORT_DASHBOARD}
        protocol: tcp
        mode: host
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == manager
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
      # - NET_RAW # ⚠️ Uncomment if using Podman
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1

networks:
  wg:
    driver: overlay  # Changed from bridge
    attachable: true
    ipam:
      driver: default
      config:
        - subnet: 192.168.177.0/24